title: Invoice Falcon
author: 622 Solutions
email: invoicefalcon.shopify@gmail.com
description: >
  Beautiful, professional invoices. Sent automatically.
baseurl: ''
url: 'https://invoicefalcon.com'
header_pages:
  - index.md
  - help.md
footer_links:
  privacy:
    link: /policy.html
    title: Privacy Policy
  terms:
    link: /terms.html
    title: Terms & Conditions
defaults:
    - scope:
        path: "assets/img"
      values:
        image: true
theme: minima
