title: Invoice Printer Pro
author: 622 Solutions
email: invoicefalcon.shopify@gmail.com
description: >
  Beautiful, customisable invoices. Sent automatically.
baseurl: ''
url: 'invoicefalcon.com'
header_pages:
  - index.md
  - faq.md
  - policy.md
  - about.md
defaults:
    - scope:
        path: "assets/img"
      values:
        image: true
theme: minima
